--- #YAML:1.0
name:               App-Templer
version:            1.4-0
abstract:           Extensible Static Site Generator.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            perl_5
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:       0
    HTML::Template:     0
    Module::Pluggable:  0
    Pod::Find:          0
    Pod::Usage:         0
    Test::Exception:    0
    Test::More:         0
    Test::NoTabs:       0
resources:
    bugtracker:  https://github.com/skx/templer/issues
    homepage:    https://github.com/skx/templer/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/skx/templer.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
